#!/usr/bin/env python

# The device your Arduino is connected to:
device = "/dev/tty.usbmodem26471"

import sys

try:
    import serial
except ImportError:
    print >>sys.stderr, "Error: pySerial not installed"
    sys.exit(1)

class Usage(Exception):
    def __init__(self, msg):
        self.msg = msg

def ring(number, device):
    port = serial.Serial(device, 9600)
    port.write(number)
    port.close()

def main():
    try:
        number = sys.argv[1] if len(sys.argv) > 1 else "1"
        if number not in map(lambda x: str(x), range(1,6)):
            raise Usage("Error: Incorrect argument")
        ring(number, device)
    except Usage, e:
        print >>sys.stderr, e.msg
        return 1

if __name__ == "__main__":
    sys.exit(main())
